galaxy_info:
  author: G Derber
  description: Installs devilspie2 package
  company: Bloodymage

  issue_tracker_url: http://github.com/bloodymage/ansible-collection-autonomy

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Rasbian
      versions:
        - 10
    - name: Debian
      versions:
        - 10
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04

  galaxy_tags:
    - bloodymage
    - packages

dependencies:
  - role: bloodymage.autonomy.collection_handlers
